
apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-deployment
  namespace: conglv
  labels:
    app: conglv-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conglv-nginx

  template:
    metadata:
      labels:
        app: conglv-nginx

    spec:
      containers:
      - name: conglv-nginx
        image: justinluong/samtest-nginx:latest
        ports:
        - containerPort: 80
